local dap, dapui = require("dap"), require("dapui")
local dapgo = require("dap-go")
dapui.setup()
dapgo.setup()
dap.listeners.before.attach.dapui_config = function()
	dapui.open()
end
dap.listeners.before.launch.dapui_config = function()
	dapui.open()
end

vim.keymap.set("n", "<leader>dc", function()
	require("dap").continue()
end, { desc = "[d]ebug [c]ontinue" })
vim.keymap.set("n", "<leader>dso", function()
	require("dap").step_over()
end, { desc = "[d]ebug [s]tep [ov]er" })
vim.keymap.set("n", "<leader>dsi", function()
	require("dap").step_into()
end, { desc = "[d]ebug [s]tep [i]nto" })
vim.keymap.set("n", "<leader>dt", function()
	require("dap-go").debug_test()
end, { desc = "[d]ebug [t]est" })
vim.keymap.set("n", "<leader>dsou", function()
	require("dap").step_out()
end, { desc = "[d]ebug [s]tep [ou]t" })
vim.keymap.set("n", "<Leader>db", function()
	require("dap").toggle_breakpoint()
end)
vim.keymap.set("n", "<Leader>dB", function()
	require("dap").set_breakpoint()
end)
vim.keymap.set("n", "<Leader>dr", function()
	require("dap").repl.open()
end)
vim.keymap.set("n", "<Leader>drl", function()
	require("dap").run_last()
end)
vim.keymap.set({ "n", "v" }, "<Leader>dh", function()
	require("dap.ui.widgets").hover()
end)
vim.keymap.set({ "n", "v" }, "<Leader>dp", function()
	require("dap.ui.widgets").preview()
end)
vim.keymap.set("n", "<Leader>df", function()
	local widgets = require("dap.ui.widgets")
	widgets.centered_float(widgets.frames)
end)
vim.keymap.set("n", "<Leader>dsc", function()
	local widgets = require("dap.ui.widgets")
	widgets.centered_float(widgets.scopes)
end)
