-- vim.keymap.set("n", "K", vim.lsp.buf.hover, {})
vim.keymap.set("n", "gd", function()
	vim.lsp.buf.definition({ reuse_win = false })
end, { desc = "[g]o to [d]eclaration", noremap = true })
-- vim.keymap.set("n", "go", vim.lsp.buf.type_definition, {})
vim.keymap.set({ "n", "v" }, "<leader>ca", vim.lsp.buf.code_action, {})
vim.keymap.set("n", "gl", vim.diagnostic.open_float, { desc = "[g]o to diagnostic f[l]oat" })
vim.keymap.set("n", "gtl", function()
	vim.diagnostic.enable(not vim.diagnostic.is_enabled())
end, { desc = "[g]o [t]oggle diagnostic f[l]oat" })
