local please = require("please")

vim.keymap.set("n", "<leader>pb", please.build, { desc = "[p]lease [b]uild" })
vim.keymap.set("n", "<leader>pt", function()
	please.test({ under_cursor = true })
end, { desc = "[p]lease [t]est under cursor" })
vim.keymap.set("n", "<leader>pd", function()
	please.debug({ under_cursor = true })
end, { desc = "[p]lease [d]ebug under cursor" })
vim.keymap.set("n", "<leader>ph", please.history, { desc = "[p]lease [h]istory" })
vim.keymap.set("n", "<leader>pch", please.clear_history, { desc = "[p]lease [c]lear [h]istory" })
vim.keymap.set("n", "<leader>pp", please.set_profile, { desc = "[p]lease set [p]rofile" })
vim.keymap.set("n", "<leader>pm", please.maximise_popup, { desc = "[p]lease [m]aximise popup" })
vim.keymap.set("n", "<leader>pj", please.jump_to_target, { desc = "[p]lease [j]ump to target" })
vim.keymap.set("n", "<leader>py", please.yank, { desc = "[p]lease [y]ank" })
