require("user.options")
require("user.keys")

require("user.autocommands")
require("user.cmp")
require("user.gitsigns")
require("user.nvim-autopairs")
require("user.nvim-tree")
require("user.nvim-treesitter")
require("user.please")
require("user.telescope")
require("user.nvim-scrollbar")
require("user.ufo")
