return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	dependencies = {
		{ "nvim-treesitter/nvim-treesitter-context", opts = {} },
		"nvim-treesitter/nvim-treesitter-textobjects",
	},
	opts = {
		ensure_installed = {
			"bash",
			"comment",
			"git_rebase",
			"gitcommit",
			"git_config",
			"gitignore",
			"go",
			"gomod",
			"gosum",
			"gowork",
			"html",
			"java",
			"javascript",
			"json",
			"lua",
			"markdown",
			"make",
			"promql",
			"proto",
			"python",
			"query",
			"regex",
			"ruby",
			"rust",
			"scheme",
			"sql",
			"ssh_config",
			"toml",
			"typescript",
			"vim",
			"vimdoc",
			"yaml",
		},
		highlight = { enable = true },
		indent = { enable = true },

		config = function(_, opts)
			require("nvim-treesitter.configs").setup(opts)
		end,
	},
}
