-- Pyrefly's own project detection fails for a subproject of a monorepo, and fails badly inside a
-- linked git worktree:
--
--  * Every first-party import in a linked worktree under an ignored path (e.g.
--    `<repo>/.claude/worktrees/<branch>`, ignored via `<repo>/.git/info/exclude`) reports
--    `Cannot find module`. Pyrefly resolves the worktree's `.git` file back to the main gitdir and
--    anchors that repo's ignore patterns at the *main* repo root, so every file in the worktree
--    matches an exclude and the project ends up with zero covered files.
--  * A subproject root (e.g. `<repo>/workers/<worker>/pyproject.toml`) gets an import root of
--    `<root>/src` only, so `src.*` imports and top-level packages shared from the repo root are
--    unresolvable. These repos hand those paths to pytest via `pythonpath = [".", "../.."]`, which
--    pyrefly does not read.
--
-- `pyrefly lsp` accepts no config overrides on the command line, so the only way to change this is
-- to hand pyrefly a config file. This module generates one per project root, in nvim's cache
-- directory, and `lsp.lua` passes its path to the server via the `python.pyrefly.configPath`
-- setting.
local M = {}

-- Excludes we have to spell out ourselves, because `disable-project-excludes-heuristics` replaces
-- pyrefly's defaults rather than appending to them. Without these, pyrefly type checks the whole
-- virtualenv. They are anchored under the project root when rendered, since pyrefly resolves
-- relative patterns against the directory holding the config file — nvim's cache directory here.
-- Note the trailing `/*`, which pyrefly's glob matcher wants, and that `venv` does not cover a
-- dotted `.venv`.
local PROJECT_EXCLUDES = {
	"**/__pycache__/**/*",
	"**/node_modules/**/*",
	"**/.venv/**/*",
	"**/venv/**/*",
}

---@param command string[]
---@param cwd string
---@return string? stdout Trimmed stdout, or nil when the command failed
local function run(command, cwd)
	local result = vim.system(command, { cwd = cwd, text = true }):wait()
	if result.code ~= 0 then
		return nil
	end
	return vim.trim(result.stdout or "")
end

---@param path string
---@return boolean
local function exists(path)
	return vim.uv.fs_stat(path) ~= nil
end

--- Pyrefly's own config wins. We only step in for projects that have not configured it.
---@param root string
---@return boolean
local function has_own_pyrefly_config(root)
	if exists(vim.fs.joinpath(root, "pyrefly.toml")) then
		return true
	end

	local pyproject = vim.fs.joinpath(root, "pyproject.toml")
	if not exists(pyproject) then
		return false
	end

	for _, line in ipairs(vim.fn.readfile(pyproject)) do
		if line:match("^%s*%[tool%.pyrefly") then
			return true
		end
	end
	return false
end

--- Root of the checkout `root` belongs to. For a linked worktree this is the worktree root, which
--- is what `../..` resolves against for these projects.
---@param root string
---@return string?
local function repo_root_of(root)
	return run({ "git", "rev-parse", "--show-toplevel" }, root)
end

---@param values string[]
---@return string
local function toml_array(values)
	local quoted = vim.tbl_map(function(value)
		return string.format("%q", value)
	end, values)
	return "[" .. table.concat(quoted, ", ") .. "]"
end

---@param root string Project root, i.e. the directory holding the subproject's pyproject.toml
---@param repo_root string Root of the checkout, i.e. the repo or worktree root
---@return string
local function render(root, repo_root)
	local lines = {
		"# Generated by ~/.config/nvim/lua/core/pyrefly_config.lua. Edits will be overwritten.",
		"project-includes = " .. toml_array({
			vim.fs.joinpath(root, "**/*.py"),
			vim.fs.joinpath(root, "**/*.pyi"),
		}),
		"project-excludes = " .. toml_array(vim.tbl_map(function(pattern)
			return vim.fs.joinpath(root, pattern)
		end, PROJECT_EXCLUDES)),
		-- Both of these are needed to undo the worktree exclusion. Either one on its own still
		-- leaves the whole tree excluded.
		"disable-project-excludes-heuristics = true",
		"use-ignore-files = false",
		-- Mirrors `pythonpath = [".", "../.."]`. Without the project root, `src.*` imports fail;
		-- without the repo root, packages shared from there (e.g. `testing`) fail.
		"search-path = " .. toml_array({ root, repo_root }),
	}

	local interpreter = vim.iter({
		vim.fs.joinpath(root, ".venv/bin/python3"),
		vim.fs.joinpath(repo_root, ".venv/bin/python3"),
	}):find(exists)
	if interpreter then
		-- Must be explicit: pyrefly looks for a virtualenv next to the config file, which now lives
		-- in nvim's cache directory.
		table.insert(lines, string.format("python-interpreter = %q", interpreter))
	end

	return table.concat(lines, "\n") .. "\n"
end

--- Path of a generated pyrefly config for `root`, or nil when pyrefly's own defaults are fine.
---@param root string
---@return string?
function M.config_path_for(root)
	if has_own_pyrefly_config(root) then
		return nil
	end

	local repo_root = repo_root_of(root)
	if not repo_root or repo_root == root then
		-- Not a subproject (or not a checkout at all), so there is no second search path to add and
		-- no ignore rule anchored above the root to work around.
		return nil
	end

	local directory = vim.fs.joinpath(vim.fn.stdpath("cache"), "pyrefly")
	vim.fn.mkdir(directory, "p")
	local path = vim.fs.joinpath(directory, vim.fs.basename(root) .. "-" .. vim.fn.sha256(root):sub(1, 12) .. ".toml")

	local contents = render(root, repo_root)
	-- Only write on change, so pyrefly does not see its config touched on every buffer open.
	if not exists(path) or table.concat(vim.fn.readfile(path), "\n") .. "\n" ~= contents then
		vim.fn.writefile(vim.split(contents, "\n", { trimempty = true }), path)
	end

	return path
end

return M
